name: Debug Deps
on: workflow_dispatch
jobs:
  debug:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Show full dependency tree
        run: cargo tree -i libp2p -e features
